CREATE TABLE HISTRNSDTL
(
HISDTLID int NOT NULL AUTO_INCREMENT,
HISHDRID int NOT NULL,
HISDTLITMID int NOT NULL,
HISDTLQTY int(4) ,
HISDTLPRICE int(4) ,
HISTIME TIMESTAMP DEFAULT now(),
PRIMARY KEY (HISDTLID),
FOREIGN KEY (HISDTLITMID) REFERENCES ITMGNL(ITMID),
FOREIGN KEY (HISHDRID) REFERENCES HISTRNSHDR(HISHDRID)
)