CREATE TABLE ITMGNL
(
ITMID int NOT NULL AUTO_INCREMENT,
ITMNAME varchar(255) NOT NULL,
ITMQTY int(7),
ITMTYPE varchar(255) NOT NULL,
PRIMARY KEY (ITMID),
FOREIGN KEY (ITMTYPE) REFERENCES TYPE(TYPEID)
)